<a href="https://colab.research.google.com/github/majorquev/DBDC_202206_Programacion_en_R_para_ciencia_de_datos/blob/main/Clase2/Clase_2_02_listas_y_dataframes_desarrollo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto). 
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [93]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
l1 <- list(num = c(11,10,22),
           letra = c("a","c","x","y"),
           pl = "Hola soy Miguel",
           mat = diag(1:5),
           lista = list(nombre = "Juan", edad = 28))

In [94]:
# estructura
l1

$num
[1] 11 10 22

$letra
[1] "a" "c" "x" "y"

$pl
[1] "Hola soy Miguel"

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$lista
$lista$nombre
[1] "Juan"

$lista$edad
[1] 28

In [95]:
str(l1)

List of 5
 $ num  : num [1:3] 11 10 22
 $ letra: chr [1:4] "a" "c" "x" "y"
 $ pl   : chr "Hola soy Miguel"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista:List of 2
  ..$ nombre: chr "Juan"
  ..$ edad  : num 28


In [96]:
length(l1)
names(l1)
class(l1)

[1] 5

[1] "num"   "letra" "pl"    "mat"   "lista"

[1] "list"

In [97]:
# Podemos guardar los objetos en slots con nombres
l2 <- list(n2 = 4, p2 = c("w","z"))
str(l2)

# names(l2) <- c("n2","p2") # otra manera de asignar los nombres

List of 2
 $ n2: num 4
 $ p2: chr [1:2] "w" "z"


In [98]:
# Podemos combinar listas
l3 <- c(l1,l2)
l3

$num
[1] 11 10 22

$letra
[1] "a" "c" "x" "y"

$pl
[1] "Hola soy Miguel"

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$lista
$lista$nombre
[1] "Juan"

$lista$edad
[1] 28


$n2
[1] 4

$p2
[1] "w" "z"

In [99]:
# Acceso mediante posición
l1[2] # lista con el segundo elemento (slot)


$letra
[1] "a" "c" "x" "y"

In [100]:
l1[c(1,3)]# lista con el primer y tercer elementos

$num
[1] 11 10 22

$pl
[1] "Hola soy Miguel"

In [101]:
l1[2][3]

$<NA>
NULL

In [102]:
class(l1[2])

[1] "list"

In [103]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]
l1[2]


$letra
[1] "a" "c" "x" "y"

In [104]:
l1[[2]]

[1] "a" "c" "x" "y"

In [105]:
# del vector l1[[2]], quiero el elememnto de posiciòn 3.
l1[[2]][3] 


[1] "x"

In [106]:
# Quero rescatar la edad de Juan
l1[[5]][2]# lista con la edad
l1[[5]][[2]]# la edad

$edad
[1] 28

[1] 28

In [107]:
# Acceso mediante nombre
l1["letra"]# lista con el vector

$letra
[1] "a" "c" "x" "y"

In [108]:
l1[["letra"]]# el vector

[1] "a" "c" "x" "y"

In [109]:
l1[["letra"]][3]

[1] "x"

In [110]:
# Edad de Juan
l1[["lista"]]["edad"]# lista con la edad

$edad
[1] 28

In [111]:
l1[["lista"]][["edad"]]# la edad

[1] 28

In [112]:
# acceso vía "$"
l1$letra # Directamente nos entrega el vector

l1$letra[3]




[1] "a" "c" "x" "y"

[1] "x"

In [113]:
# Edad de juan
l1$lista$edad # Es el elemento dentro de la entrada llamada "edad" (NO es una lista)

[1] 28

In [114]:
# para saber el largo de la lista/vector
length(l1)
# Para obtener los nombres de la lista
names(l1)
# si quisiéramos renombrar los slots:
names(l1)[5] <- "persona"

[1] 5

[1] "num"   "letra" "pl"    "mat"   "lista"

In [115]:
l1

$num
[1] 11 10 22

$letra
[1] "a" "c" "x" "y"

$pl
[1] "Hola soy Miguel"

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$persona
$persona$nombre
[1] "Juan"

$persona$edad
[1] 28

In [116]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando
l1[["nueva_persona"]] <- "Pedro"
str(l1)

List of 6
 $ num          : num [1:3] 11 10 22
 $ letra        : chr [1:4] "a" "c" "x" "y"
 $ pl           : chr "Hola soy Miguel"
 $ mat          : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ persona      :List of 2
  ..$ nombre: chr "Juan"
  ..$ edad  : num 28
 $ nueva_persona: chr "Pedro"


In [117]:
# Otra opciòn usando "$"

l1$otro_num <- c(1,7)

In [118]:
str(l1)

List of 7
 $ num          : num [1:3] 11 10 22
 $ letra        : chr [1:4] "a" "c" "x" "y"
 $ pl           : chr "Hola soy Miguel"
 $ mat          : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ persona      :List of 2
  ..$ nombre: chr "Juan"
  ..$ edad  : num 28
 $ nueva_persona: chr "Pedro"
 $ otro_num     : num [1:2] 1 7


In [119]:
# podemos modificar elementos dentro de un slot
#Ej: Modificar la edad de Juan

l1$persona$edad <- 30 


In [120]:
str(l1)

List of 7
 $ num          : num [1:3] 11 10 22
 $ letra        : chr [1:4] "a" "c" "x" "y"
 $ pl           : chr "Hola soy Miguel"
 $ mat          : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ persona      :List of 2
  ..$ nombre: chr "Juan"
  ..$ edad  : num 30
 $ nueva_persona: chr "Pedro"
 $ otro_num     : num [1:2] 1 7


In [121]:
l1$otro_num <- NULL # Podemos eliminar la entrada "otro_num"

In [122]:
str(l1)

List of 6
 $ num          : num [1:3] 11 10 22
 $ letra        : chr [1:4] "a" "c" "x" "y"
 $ pl           : chr "Hola soy Miguel"
 $ mat          : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ persona      :List of 2
  ..$ nombre: chr "Juan"
  ..$ edad  : num 30
 $ nueva_persona: chr "Pedro"


In [123]:
# Héctor pregunta si se puede cambiar el tipo de dato.

# Ej: Cambiar el tipo de dato de la edad de Juan a "character"
l1$persona$edad <- as.character(l1$persona$edad)


In [124]:
str(l1)

List of 6
 $ num          : num [1:3] 11 10 22
 $ letra        : chr [1:4] "a" "c" "x" "y"
 $ pl           : chr "Hola soy Miguel"
 $ mat          : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ persona      :List of 2
  ..$ nombre: chr "Juan"
  ..$ edad  : chr "30"
 $ nueva_persona: chr "Pedro"


### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí. 

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.
 
 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [125]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)

df <- data.frame(nombre = c("Juan", "Diego", "Miguel"),
                 edad = c(25,40,33),
                 id = 1:3
                 )

df

nombre edad id
1 Juan   25   1 
2 Diego  40   2 
3 Miguel 33   3

In [149]:
dim(df)

[1] 3 5

In [126]:
str(df)

'data.frame':	3 obs. of  3 variables:
 $ nombre: chr  "Juan" "Diego" "Miguel"
 $ edad  : num  25 40 33
 $ id    : int  1 2 3


In [127]:
# Acceso a columnas de un data.frame
# Se mantiene la lógica de acceso a los sots de una lista.
df["nombre"] # es el dataframe (antes lista) con el vector
df[["nombre"]]# El vector de la columna nombre
df$nombre




nombre
1 Juan  
2 Diego 
3 Miguel

[1] "Juan"   "Diego"  "Miguel"

[1] "Juan"   "Diego"  "Miguel"

In [128]:
##  Ganamos acceso como matriz
# segunda fila de df
df[2,]

# segunda columna y segunda fila
df[2,2]



nombre edad id
2 Diego  40   2

[1] 40

In [129]:
df[,"edad"]# El vector de edades (hereda acceso por nombres en una matriz)
df[2,"edad"]# Segunda fila de la columna "edad"

[1] 25 40 33

[1] 40

In [130]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista
df$tiene_ccte <- c(T,F,T)

In [131]:
df[["nombre_mascota"]] <- c("bobi", "akira","daenarys")

In [132]:
df

nombre edad id tiene_ccte nombre_mascota
1 Juan   25   1   TRUE      bobi          
2 Diego  40   2  FALSE      akira         
3 Miguel 33   3   TRUE      daenarys

In [133]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar col1y col3

# Referenciando el nombre de las columnas
df[,c("nombre","nombre_mascota")]# pensando como en una matriz
df[c("nombre","nombre_mascota")]# Pensando como en una lista


nombre nombre_mascota
1 Juan   bobi          
2 Diego  akira         
3 Miguel daenarys

nombre nombre_mascota
1 Juan   bobi          
2 Diego  akira         
3 Miguel daenarys

In [134]:
# Pensar como matriz nos da ventaja.
# Traer las filas 1 y 3, y las columnas nombre y nombre_mascota
df[c(1,3), c("nombre","nombre_mascota")]

nombre nombre_mascota
1 Juan   bobi          
3 Miguel daenarys

In [135]:
# Referenciando las posiciones de las columnas
# Primera y tercera columas
df[,c(1,3)]

nombre id
1 Juan   1 
2 Diego  2 
3 Miguel 3

In [136]:
df

nombre edad id tiene_ccte nombre_mascota
1 Juan   25   1   TRUE      bobi          
2 Diego  40   2  FALSE      akira         
3 Miguel 33   3   TRUE      daenarys

In [137]:
df$edad > 30


[1] FALSE  TRUE  TRUE

In [138]:
df[df$edad > 30,]# Consultamos todas las columnas donde la edad es mayor a 30.

nombre edad id tiene_ccte nombre_mascota
2 Diego  40   2  FALSE      akira         
3 Miguel 33   3   TRUE      daenarys

In [139]:
df[df$edad > 30,"nombre_mascota"] # Si solo queremos los nombres de mascota de los duenños mayores de 30 años


[1] "akira"    "daenarys"

In [140]:
df[df$edad > 30,]$nombre_mascota 

[1] "akira"    "daenarys"

In [141]:
# Cambiar nombre de una columna
names(df)

[1] "nombre"         "edad"           "id"             "tiene_ccte"    
[5] "nombre_mascota"

In [142]:
colnames(df)

[1] "nombre"         "edad"           "id"             "tiene_ccte"    
[5] "nombre_mascota"

In [143]:
colnames(df)[4] <- "tiene_cuenta_corriente"

In [144]:
df

nombre edad id tiene_cuenta_corriente nombre_mascota
1 Juan   25   1   TRUE                  bobi          
2 Diego  40   2  FALSE                  akira         
3 Miguel 33   3   TRUE                  daenarys

In [145]:
names(df) == "tiene_cuenta_corriente"

[1] FALSE FALSE FALSE  TRUE FALSE

In [146]:
names(df)[names(df) == "tiene_cuenta_corriente"]

[1] "tiene_cuenta_corriente"

In [147]:
names(df)[names(df) == "tiene_cuenta_corriente"] <- "tiene_tc"

In [148]:
df

nombre edad id tiene_tc nombre_mascota
1 Juan   25   1   TRUE    bobi          
2 Diego  40   2  FALSE    akira         
3 Miguel 33   3   TRUE    daenarys

In [162]:
# Como agregar una fila
fila <- data.frame(nombre = "Harold",
                   edad = 25,
                   id = 4,
                   tiene_tc = TRUE,
                   nombre_mascota = "Kayser")

df <- rbind(df,fila) # df.append(fila) simil en python

# dplyr::bind_rows (prox clase)

In [163]:
df

nombre edad id tiene_tc nombre_mascota
1 Juan   25   1   TRUE    bobi          
2 Diego  40   2  FALSE    akira         
3 Miguel 33   3   TRUE    daenarys      
4 Harold 25   4   TRUE    Kayser

In [164]:
fila2 <- data.frame(nombre = "Harold",
                   edad = 25,
                   id = 4,
                   tiene_tc = TRUE,
                   nombre_mascota = NA
                   )
fila2

nombre edad id tiene_tc nombre_mascota
1 Harold 25   4  TRUE     NA

In [160]:
rbind(df, fila2)

nombre edad id tiene_tc nombre_mascota
1 Juan   25   1   TRUE    bobi          
2 Diego  40   2  FALSE    akira         
3 Miguel 33   3   TRUE    daenarys      
4 Harold 25   4   TRUE    NA

In [165]:
fila3 <- data.frame(nombre = "Ana",
                   edad = 25,
                   tiene_tc = TRUE,
                   id = 5,
                   nombre_mascota = "Oso"
                   )
fila3

nombre edad tiene_tc id nombre_mascota
1 Ana    25   TRUE     5  Oso

In [166]:
rbind(df,fila3) # matchea por nombre :D

nombre edad id tiene_tc nombre_mascota
1 Juan   25   1   TRUE    bobi          
2 Diego  40   2  FALSE    akira         
3 Miguel 33   3   TRUE    daenarys      
4 Harold 25   4   TRUE    Kayser        
5 Ana    25   5   TRUE    Oso