<a href="https://colab.research.google.com/github/majorquev/DBDC_202206_Programacion_en_R_para_ciencia_de_datos/blob/main/Clase2/Clase_2_01_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una matriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo. 
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.
 
 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [2]:
?matrix

In [3]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos

A <- matrix(c(9,10,4,6,7,8), ncol = 3, nrow = 2)
A
B <- matrix(c(9,10,4,6,7,8), ncol = 3, nrow = 2, byrow = TRUE)
B

[,1] [,2] [,3]
[1,]  9   4    7   
[2,] 10   6    8

[,1] [,2] [,3]
[1,] 9    10   4   
[2,] 6     7   8

In [4]:
# clase y atributo dim
class(B)

[1] "matrix" "array"

In [5]:
dim(B)

[1] 2 3

In [7]:
# Cantidad de columnas
dim(B)[2]
# Cantidad de filas
dim(B)[1]

[1] 3

[1] 2

In [9]:
# nrow(): cantidad de filas
nrow(B)
# ncol(): cantidad de columnas
ncol(B)

[1] 2

[1] 3

In [11]:
# Genere dos vectores del mismo largo y forme una matriz.
v1 <- 1:5
v2 <- seq(1,2,length.out = 5) 
v1;v2

[1] 1 2 3 4 5

[1] 1.00 1.25 1.50 1.75 2.00

In [14]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind

C <- cbind(v1,v2)
C

D <- rbind(v1,v2)
D

v1 v2  
[1,] 1  1.00
[2,] 2  1.25
[3,] 3  1.50
[4,] 4  1.75
[5,] 5  2.00

[,1] [,2] [,3] [,4] [,5]
v1 1    2.00 3.0  4.00 5   
v2 1    1.25 1.5  1.75 2

In [18]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)

cbind(c(3,5,7,9,11,15), c(10,11))



[,1] [,2]
[1,]  3   10  
[2,]  5   11  
[3,]  7   10  
[4,]  9   11  
[5,] 11   10  
[6,] 15   11

In [19]:
# Nota: Si queremos dejar los NA`s debemos declararlos
cbind(c(3,5,7,9,11,15), c(10,11,NA,NA,NA,NA))

[,1] [,2]
[1,]  3   10  
[2,]  5   11  
[3,]  7   NA  
[4,]  9   NA  
[5,] 11   NA  
[6,] 15   NA

In [20]:
# función diag para la definición de matrices diagonales
#?diag 

diag(c(1,3,6,9))



[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    3    0    0   
[3,] 0    0    6    0   
[4,] 0    0    0    9

In [25]:
B

[,1] [,2] [,3]
[1,] 9    10   4   
[2,] 6     7   8

In [26]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# quiero rescatar el elemento "(2,1)"
B[2,1]

# CUIDADO:No es lo mismo que 
B[c(2,1)] # R entiende también la matriz como un gran vector (por columnas) y lo anterior retorna los elmentos 2 y 1 de dicho vector

[1] 6

[1] 6 9

In [28]:
# Para acceder a una fila completa
B[2,]#Segunda fila


# Para acceder a una columna completa
B[,3] #Tercera columna


[1] 6 7 8

[1] 4 8

In [29]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el 7 por un 99 (el 7 de la pos 2,2)
B[2,2] <- 99
B

[,1] [,2] [,3]
[1,] 9    10   4   
[2,] 6    99   8

In [33]:
C

v1 v2  
[1,] 1  1.00
[2,] 2  1.25
[3,] 3  1.50
[4,] 4  1.75
[5,] 5  2.00

In [34]:
# Acceso mediante nombres
colnames(C)
rownames(C)

[1] "v1" "v2"

NULL

In [38]:
paste("hola", "miguel", sep = "")# concatenar strings

[1] "holamiguel"

In [39]:
paste0("hola","miguel")

[1] "holamiguel"

In [40]:
paste0("fila_",1:5)

[1] "fila_1" "fila_2" "fila_3" "fila_4" "fila_5"

In [41]:
# podemos definir los nombres en filas/columnas

rownames(C) <- paste0("fila_",1:5)

In [42]:
C

v1 v2  
fila_1 1  1.00
fila_2 2  1.25
fila_3 3  1.50
fila_4 4  1.75
fila_5 5  2.00

In [43]:
# Acceso mediante nombres
C["fila_3","v2"]# mismo que C[3,2]

[1] 1.5

In [46]:
# Acceso mediante "indicatrices" lógicas 
#Quiero obtener los elementos (1,1) y (3,2) de C
# 1: Crear una matriz de 5x2 con TRUE en dichas posiciones y FALSE en las restantes.
ind <- cbind(c(T,F,F,F,F),c(F,F,T,F,F))
ind


[,1]  [,2] 
[1,]  TRUE FALSE
[2,] FALSE FALSE
[3,] FALSE  TRUE
[4,] FALSE FALSE
[5,] FALSE FALSE

In [47]:
# Podemos evaluar las casillas de una matriz mediante sentencias lógicas
C[ind]

[1] 1.0 1.5

In [50]:
C[C>=1.75] # Lo anterior nos permite generar este tipo de consultas. 
# Nos retorna los elementos que son mayores o iguales a 1.75.

[1] 2.00 3.00 4.00 5.00 1.75 2.00

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [21]:
# transponer una matriz
B

[,1] [,2] [,3]
[1,] 9    10   4   
[2,] 6     7   8

In [22]:
t(B)

[,1] [,2]
[1,]  9   6   
[2,] 10   7   
[3,]  4   8

In [52]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices
M1 <- matrix(c(1,1,2,5), ncol = 2) 
M2 <- matrix(c(1,3,5,7), ncol = 2) 

In [54]:
M1;M2

[,1] [,2]
[1,] 1    2   
[2,] 1    5

[,1] [,2]
[1,] 1    5   
[2,] 3    7

In [53]:
M1+M2

[,1] [,2]
[1,] 2     7  
[2,] 4    12

In [55]:
# Multiplicación de matrices
M1 * M2 # multiplicación componente a componente


[,1] [,2]
[1,] 1    10  
[2,] 3    35

In [56]:
M1 %*% M2

[,1] [,2]
[1,]  7   19  
[2,] 16   40

In [57]:
# podemos calcular determinantes
# ?det
det(M2)


[1] -8

In [60]:
# Podemos invertir matrices
# ?solve

solve(M2)

solve(M2)%*%M2

[,1]         [,2]        
[1,] 1.000000e+00 1.110223e-16
[2,] 2.775558e-17 1.000000e+00